name = "aoc-2024"
version = "0.1.0"
defaultTargets = ["day1"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.14.0"

[[lean_lib]]
name = "Aoc2024"

[[lean_exe]]
name = "day1"
root = "Day1"

[[lean_exe]]
name = "day2"
root = "Day2"

[[lean_exe]]
name = "day3"
root = "Day3"

[[lean_exe]]
name = "day4"
root = "Day4"

[[lean_exe]]
name = "day5"
root = "Day5"

[[lean_exe]]
name = "day6"
root = "Day6"

[[lean_exe]]
name = "day7"
root = "Day7"

[[lean_exe]]
name = "day8"
root = "Day8"

[[lean_exe]]
name = "day9"
root = "Day9"

[[lean_exe]]
name = "day10"
root = "Day10"

[[lean_exe]]
name = "day11"
root = "Day11"

[[lean_exe]]
name = "day12"
root = "Day12"

[[lean_exe]]
name = "day13"
root = "Day13"

[[lean_exe]]
name = "day14"
root = "Day14"

[[lean_exe]]
name = "day15"
root = "Day15"

[[lean_exe]]
name = "day16"
root = "Day16"

[[lean_exe]]
name = "day17"
root = "Day17"

[[lean_exe]]
name = "day18"
root = "Day18"

[[lean_exe]]
name = "day19"
root = "Day19"
