name = "aoc-2024"
version = "0.1.0"
defaultTargets = ["day1"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.14.0"

[[lean_lib]]
name = "Aoc2024"

[[lean_exe]]
name = "day1"
root = "Day1"

[[lean_exe]]
name = "day2"
root = "Day2"

[[lean_exe]]
name = "day3"
root = "Day3"

[[lean_exe]]
name = "day4"
root = "Day4"

[[lean_exe]]
name = "day5"
root = "Day5"

[[lean_exe]]
name = "day6"
root = "Day6"

[[lean_exe]]
name = "day7"
root = "Day7"
